language: generic

git:
  depth: 1

env:
  global:
    - export OMP_NUM_THREADS=2
    - export CXX_STANDARD=11
    - export MONOLITH=ON

matrix:
  include:
    - name: "macOS 10.14: Apple Clang"
      env:
        - CC=cc
        - CXX=c++
        - CACHE_NAME=OSX_10_14_APPLE_CLANG
      os: osx
      osx_image: xcode10.3
      workspaces:
        create:
          name: brew_cache_14
          paths: &cache_paths
            - $HOME/Library/Caches/Homebrew
            - /usr/local/Homebrew
            - $HOME/local_bottle_metadata
      cache: &cache_dirs
        directories:
          - $HOME/.cache
          - $HOME/Library/Caches/Homebrew
          - /usr/local/Homebrew
          - $HOME/local_bottle_metadata
      before_cache: &before_cache_osx |
        if [ -e "$(brew --repository)/Library/Taps/homebrew/homebrew-cask/homebrew-cask" ]; then
            rm -rf "$(brew --repository)/Library/Taps/homebrew/homebrew-cask/homebrew-cask"
        fi
        brew_cache_cleanup
      before_install: |
        source travis_config.sh
        update_and_install_packages
        brew_cache_cleanup

    - name: "macOS 10.14: llvm 9"
      env:
        - CC=/usr/local/opt/llvm@9/bin/clang
        - CXX=/usr/local/opt/llvm@9/bin/clang++
        - CACHE_NAME=OSX_10_14_LLVM9
      os: osx
      osx_image: xcode10.3
      workspaces:
          use: brew_cache_14
      cache: *cache_dirs
      before_cache: *before_cache_osx
      before_install: |
        source travis_config.sh
        update_and_install_packages llvm@9
        brew_cache_cleanup

    - name: "macOS 10.14: llvm 4"
      env:
        - CC=/usr/local/opt/llvm@4/bin/clang
        - CXX=/usr/local/opt/llvm@4/bin/clang++
        - CACHE_NAME=OSX_10_14_LLVM4
      os: osx
      osx_image: xcode10.3
      workspaces:
          use: brew_cache_14
      cache: *cache_dirs
      before_cache: *before_cache_osx
      before_install: |
        source travis_config.sh
        update_and_install_packages llvm@4
        brew_cache_cleanup

    - name: "macOS 10.14: GCC 9"
      env:
        - CC=/usr/local/opt/gcc/bin/gcc-9
        - CXX=/usr/local/opt/gcc/bin/g++-9
        - CACHE_NAME=OSX_10_14_GCC9
      os: osx
      osx_image: xcode10.3
      workspaces:
          use: brew_cache_14
      cache: *cache_dirs
      before_cache: *before_cache_osx
      before_install: |
        source travis_config.sh
        update_and_install_packages gcc@9
        brew_cache_cleanup

    - name: "macOS 10.14: GCC 6"
      env:
        - CC=/usr/local/opt/gcc@6/bin/gcc-6
        - CXX=/usr/local/opt/gcc@6/bin/g++-6
        - CACHE_NAME=OSX_10_14_GCC6
      os: osx
      osx_image: xcode10.3
      workspaces:
          use: brew_cache_14
      cache: *cache_dirs
      before_cache: *before_cache_osx
      before_install: |
        source travis_config.sh
        update_and_install_packages gcc@6
        brew_cache_cleanup

    - name: "macOS 10.12: Apple Clang"
      env:
        - CC=cc
        - CXX=c++
        - CACHE_NAME=OSX_10_12_APPLE_CLANG
      os: osx
      osx_image: xcode8.3
      workspaces:
        create:
          name: brew_cache_12
          paths: *cache_paths
      cache: *cache_dirs
      before_cache: *before_cache_osx
      before_install: |
        source travis_config.sh
        update_and_install_packages python3
        brew_cache_cleanup

    - name: "macOS 10.12: Apple Clang, non-monolith"
      env:
        - CC=cc
        - CXX=c++
        - CACHE_NAME=OSX_10_12_APPLE_CLANG
      os: osx
      osx_image: xcode8.3
      workspaces:
        use: brew_cache_12
      cache: *cache_dirs
      script:
        - $CXX --version
        - mkdir build_non_monolith && cd "$_"
        - cmake -DNETWORKIT_MONOLITH=OFF -DNETWORKIT_BUILD_TESTS=ON -DCMAKE_BUILD_TYPE=Debug ..
        - make -j2
        - ctest -V
      before_cache: *before_cache_osx
      before_install: |
        source travis_config.sh
        update_and_install_packages python3
        brew_cache_cleanup

    # Test with sanitizers, and upload coverage results to coveralls.
    - name: "Linux: Core build, sanitizers, coverage"
      compiler: gcc
      os: linux
      dist: xenial
      addons:
        apt:
          packages:
            - python3-pip
            - python3-venv
      script:
        - python3 -m venv pyenv && . pyenv/bin/activate
        - pip3 install --upgrade pip
        - pip3 install setuptools cpp-coveralls
        - mkdir build && cd "$_"
        - cmake -DNETWORKIT_BUILD_TESTS=ON -DCMAKE_BUILD_TYPE=Debug -DNETWORKIT_WITH_SANITIZERS=leak -DNETWORKIT_COVERAGE=ON ..
        - make -j2
        - ctest -V
      after_success:
        - cd ..
        - coveralls -E ".*test/.*" -E ".*CMakeFiles.*" --exclude extlibs --exclude pyenv --exclude scripts --root .

    - name: "Linux: GCC 9"
      env:
        - CC=gcc-9
        - CXX=g++-9
      os: linux
      dist: xenial
      addons: &gcc9
        apt:
          sources:
            - sourceline: 'ppa:ubuntu-toolchain-r/test'
          packages:
            - g++-9
            - python3-pip
            - python3-venv
      before_install: &gcc9bi
        - sudo apt-get install gcc-9 -y

    - name: "Linux: GCC 4.9"
      env:
        - CC=gcc-4.9
        - CXX=g++-4.9
      os: linux
      dist: xenial
      addons:
        apt:
          sources:
            - sourceline: 'ppa:ubuntu-toolchain-r/test'
          packages:
            - cmake
            - g++-4.9
            - python3-pip
            - python3-venv

    - name: "Linux: Clang 8"
      env:
        - CC=clang-8
        - CXX=clang++-8
      os: linux
      dist: xenial
      addons:
        apt:
          sources:
            - 'ubuntu-toolchain-r-test'
            - 'llvm-toolchain-xenial-8'
          packages:
            - clang-8
            - libiomp-dev
            - python3-pip
            - python3-venv
      before_install:
        - sudo apt-get install clang-8 -y

    - name: "Linux: Clang 3.8"
      env:
        - CC=clang-3.8
        - CXX=clang++-3.8
      os: linux
      dist: xenial
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - clang-3.8
            - libiomp-dev
            - python3-pip
            - python3-venv
      before_install:
        - sudo apt-get install clang-3.8 -y

    - name: "Linux: GCC 9, Core build, debugging"
      env:
        - CC=gcc-9
        - CXX=g++-9
      os: linux
      dist: xenial
      addons: *gcc9
      script: &script_cpp_only
        - $CXX --version
        - mkdir debug_test && cd "$_"
        - cmake -DNETWORKIT_BUILD_TESTS=ON -DNETWORKIT_MONOLITH=$MONOLITH -DNETWORKIT_CXX_STANDARD=$CXX_STANDARD -DNETWORKIT_WARNINGS=ON -DCMAKE_BUILD_TYPE=Debug ..
        - make -j2
        - ctest -V
      before_install: &gcc9bi

    - name: "Linux: GCC 9, Core build, non-monolithic"
      env:
        - CC=gcc-9
        - CXX=g++-9
        - MONOLITH=OFF
      os: linux
      dist: xenial
      addons: *gcc9
      script: *script_cpp_only
      before_install: &gcc9bi

    # Finally, test conformance to newer versions of the C++ standard.
    - name: "Linux: GCC 9, C++14 conformance"
      env:
        - CC=gcc-9
        - CXX=g++-9
        - CXX_STANDARD=14
      os: linux
      dist: xenial
      addons: *gcc9
      script: *script_cpp_only
      before_install: &gcc9bi

    - name: "Linux: GCC 9, C++17 conformance"
      env:
        - CC=gcc-9
        - CXX=g++-9
        - CXX_STANDARD=17
      os: linux
      dist: xenial
      addons: *gcc9
      script: *script_cpp_only
      before_install: &gcc9bi

    - name: Documentation only
      compiler: gcc
      os: linux
      dist: xenial
      addons:
        apt:
          packages:
            - python3-pip
            - python3-venv
            - doxygen
      script:
        - set -e
        - python3 -m venv pyenv && . pyenv/bin/activate
        - pip3 install --upgrade pip
        # cython is required because git does not contain _NetworKit.
        - pip3 install cython
        # sphinx_bootstrap_theme is required to build the documentation.
        - pip3 install sphinx sphinx_bootstrap_theme
        # Build the C++ core library (no need for optimizations).
        - mkdir core_build && cd "$_"
        - cmake -DCMAKE_BUILD_TYPE=Debug -DNETWORKIT_CXX_STANDARD=$CXX_STANDARD -DNETWORKIT_WARNINGS=ON ..
        - make -j2
        - cd ..
        # Build the Python extension.
        - export CMAKE_LIBRARY_PATH=${CMAKE_LIBRARY_PATH:+$CMAKE_LIBRARY_PATH:}$(pwd)/core_build
        - export LD_LIBRARY_PATH=${LD_LIBRARY_PATH:+$LD_LIBRARY_PATH:}$(pwd)/core_build
        - NETWORKIT_PARALLEL_JOBS=2 python3 ./setup.py build_ext --inplace --networkit-external-core
        - NETWORKIT_PARALLEL_JOBS=2 pip3 install -e .
        # Build the documentation.
        - cd core_build
        - make docs
        - touch htmldocs/.nojekyll
        - rm -rf htmldocs/{.buildinfo,.doctrees}
      deploy:
        provider: pages
        skip-cleanup: true
        github-token: $SECRET_DEPLOY_GITHUB_PAGES
        local-dir: core_build/htmldocs
        repo: networkit/dev-docs
        target-branch: master
        on:
          branch: Dev

    - name: "Style guide compliance"
      os: linux
      dist: xenial
      script:
        - set -e
        - python3 extrafiles/tooling/CppIndentation.py

script:
 - $CXX --version
 - python3 --version
 - cmake --version

 - python3 -m venv pyenv && . pyenv/bin/activate
 - pip3 install --upgrade pip
 # cython is required because git does not contain _NetworKit.
 # ipython is required for tests.
 - pip3 install cython ipython jupyter

 # First, build the C++ core library and run C++ tests.
 - mkdir core_build && cd "$_"
 - cmake -DNETWORKIT_BUILD_TESTS=ON -DCMAKE_BUILD_TYPE=Release -DNETWORKIT_CXX_STANDARD=$CXX_STANDARD -DNETWORKIT_WARNINGS=ON -DNETWORKIT_WARNINGS_AS_ERRORS=ON ..
 - make -j2
 - UBSAN_OPTIONS=print_stacktrace=1:halt_on_error=1 ASAN_OPTIONS=abort_on_error=1 ctest -V
 - cd ..

 # Finally, build the Python extension and run Python tests.
 - export CMAKE_LIBRARY_PATH=${CMAKE_LIBRARY_PATH:+$CMAKE_LIBRARY_PATH:}$(pwd)/core_build
 - export LD_LIBRARY_PATH=${LD_LIBRARY_PATH:+$LD_LIBRARY_PATH:}$(pwd)/core_build
 - NETWORKIT_PARALLEL_JOBS=2 python3 ./setup.py build_ext --inplace --networkit-external-core
 - NETWORKIT_PARALLEL_JOBS=2 pip3 install -e .
 - python3 -m unittest discover -v networkit/test/

 # Test Jupyter-notebooks
 - python3 notebooks/test_notebooks.py 'notebooks/'

notifications:
  email: false
